{% set version = '9.8-3' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-fields
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/fields_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/fields/fields_{{ version }}.tar.gz
  sha256: 010676e009d48ff605d9881bcedb903b95bc4a271da47eb629d5cbcf1a323de1

build:
  merge_build_host: True  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('fortran') }}        # [not win]
    - {{ compiler('m2w64_fortran') }}  # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-maps
    - r-spam
  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-maps
    - r-spam

test:
  commands:
    - $R -e "library('fields')"           # [not win]
    - "\"%R%\" -e \"library('fields')\""  # [win]

about:
  home: https://github.com/NCAR/Fields
  license: GPL (>= 2)
  summary: For curve, surface and function fitting with an emphasis on splines, spatial data,
    geostatistics,  and spatial statistics. The major methods include cubic, and thin
    plate splines, Kriging, and compactly supported covariance functions for large data
    sets. The splines and Kriging methods are supported by functions that can determine
    the smoothing parameter (nugget and sill variance) and other covariance function
    parameters by cross validation and also by restricted maximum likelihood. For Kriging
    there is an easy to use function that also estimates the correlation scale (range
    parameter).  A major feature is that any covariance function implemented in R and
    following a simple format can be used for spatial prediction. There are also many
    useful functions for plotting and working with spatial data as images. This package
    also contains an implementation of sparse matrix methods for large spatial data
    sets and currently requires the sparse matrix (spam) package. Use help(fields) to
    get started and for an overview.  The fields source code is deliberately commented
    and provides useful explanations of numerical details as a companion to the manual
    pages. The commented source code can be viewed by expanding  source code version
    and looking in the R subdirectory. The reference for fields can be generated by
    the citation function in R and has DOI <doi:10.5065/D6W957CT>. Development of this
    package was supported in part by the National Science Foundation  Grant 1417857
    and the National Center for Atmospheric Research. See the Fields URL for a vignette
    on using this package and some background on spatial statistics.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: fields
# Version: 9.8-3
# Date: 2019-05-28
# Title: Tools for Spatial Data
# Authors@R: c( person("Douglas", "Nychka", role = c("aut", "cre"), email = "douglasnychka@gmail.com"), person("Reinhard", "Furrer", role = c("aut"), email = "reinhard.furrer@math.uzh.ch"), person("John", "Paige", role = c("aut"), email = "paigejo@uw.edu"), person("Stephan", "Sain", role = "aut", email = "sainsr2@gmail.com"), person("University Corporation for Atmospheric Research", role="cph", email="nychka@ucar.edu") )
# Author: Douglas Nychka [aut, cre], Reinhard Furrer [aut], John Paige [aut], Stephan Sain [aut], University Corporation for Atmospheric Research [cph]
# Maintainer: Douglas Nychka <douglasnychka@gmail.com>
# Description: For curve, surface and function fitting with an emphasis on splines, spatial data, geostatistics,  and spatial statistics. The major methods include cubic, and thin plate splines, Kriging, and compactly supported covariance functions for large data sets. The splines and Kriging methods are supported by functions that can determine the smoothing parameter (nugget and sill variance) and other covariance function parameters by cross validation and also by restricted maximum likelihood. For Kriging there is an easy to use function that also estimates the correlation scale (range parameter).  A major feature is that any covariance function implemented in R and following a simple format can be used for spatial prediction. There are also many useful functions for plotting and working with spatial data as images. This package also contains an implementation of sparse matrix methods for large spatial data sets and currently requires the sparse matrix (spam) package. Use help(fields) to get started and for an overview.  The fields source code is deliberately commented and provides useful explanations of numerical details as a companion to the manual pages. The commented source code can be viewed by expanding  source code version and looking in the R subdirectory. The reference for fields can be generated by the citation function in R and has DOI <doi:10.5065/D6W957CT>. Development of this package was supported in part by the National Science Foundation  Grant 1417857 and the National Center for Atmospheric Research. See the Fields URL for a vignette on using this package and some background on spatial statistics.
# License: GPL (>= 2)
# URL: https://github.com/NCAR/Fields
# Depends: R (>= 3.0), methods, spam, maps
# NeedsCompilation: yes
# Packaged: 2019-05-28 19:23:48 UTC; nychka
# Repository: CRAN
# Date/Publication: 2019-05-28 21:20:03 UTC
