appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: OV0cRjMPtPB/+uBYQBKi2E+JwmJ2ZbS4yc8tkFXA3fHc1eCKWKWbWRm+oPlsCtY2RjMg4V6AhLvkj8/eHM8mrErmk86gNTs+YN2apY3UsznFeCYm5NYVCs1WKodLZsT2YXL3XA4TTwt9n05SalWJ91vynzVfLU5Gw3Myjwn33/YIcUfw/8ehVoyzYOBZm6FWYGTYCdx+GAii2guItQAut4r5PjhrgoddiR5D36cmMr3qOR/xyoHY3Oc6x9MF6A+k1cbgz3W1YzeBsnuZX0oSWO5gq+K779cARAdV1l2s2Z90+k9jHkDkBsiB0123defIFblAkbr728PgnTtvC1pS0DhOShPy64YLBeVv5yDVvXZ2zBLltPE7WkS2v5issoCa2uAHsFLfTdd5uMhNcepnQp3fwVWvDr2TJnxNnkplHwjIwdO2zePlc6wTvs7smdgIFkaHaONi33flotEjrRwrDYK08GclXlMZo/cdc2jv5+XAiRqJTj+ZYdxVF6dhmBT2j2CYjviIY8MPBiZqWQg8eMBdY98wK2NrGZqNkO6mW61gUV0R4DOSzJfWBP8HWAtdtckNnxNbeXr0bnjx3rqC3ohAt29YIdXIOKlpHAAtCroWhiyDP9GNZmHp9ZcuTKu9HhU5qtEnDua9DvfXg/EGQIX4JWWTpxd/hnNnYPiWw6M=}
