travis:
  secure:
    BINSTAR_TOKEN: Ml+wNo33sWhHA94q6993yqDRXLVMYNEcERZ9NAfdQvkLeOSV+mOqPjwwWgwWsbRBkV/x2kX8OJqcQD+CVHne7+TmJ3CX5v5DcWD0z80OOZZM8w4v5ekkkNk2J+EAEdm/eIL11HMbqiFQYQo9mu9HIvfoHSmpD6Z0GilOmcNxtZdPUAP58v7DNroEgNW+1j5xn+mOUMhd1BTB7o8klc/4qhrEMuZWZF8EYNtpLdhCk3nLQKh2AilgHQqZvxBUIcUCB31YVRPGoIy86zr43fH+xcBjywDVj08X2B25yiwbEWVsGvisvdG3MrV+FLUqWIoGJDlCQNVvkSClLGYpW75MqqBkg6yKkrcmvj4kaNXUOGlTf6oZkV4+XlkWNMCL/gNON3miigx0vXSNKNnueW2sj3ho4tqxdg6+exHTd3t7tCdQPh9LSdowxvodBpP7u3WfteemxKfV7SWzRCk5eqCx296nU0x70h4MwQVLa2DFfQDsmBBbQECAU8ldaXdz9t+/SHxpjSBPnUN9Ko86xvyY2brVKAIj/GTv8SaY5DdY3qb3rvA64mPT735sW+OeWQLRrWTdNEfVVsRLz73abkoWSda8foRswZ0/b5p46+9bhUzAYamxDcyqWPZmI9dkfJeHxPMfS+qnZnIc42QtFdY9nmGHkY8fwfOfCK70Gtu+uKI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
